name: sync to gitee
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: sync github -> gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: 'github/qiutongxue'
          dst: 'gitee/${{ secrets.GITEE_USERNAME }}'
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token:  ${{ secrets.GITEE_TOKEN }}
          static_list: 'poe-dat-schema-sync'
